namespace ToolRegFB
{
	// Token: 0x0200002B RID: 43
	public partial class frmLoginUser : global::System.Windows.Forms.Form
	{
		// Token: 0x060001EA RID: 490 RVA: 0x00014F38 File Offset: 0x00013138
		protected override void Dispose(bool disposing)
		{
			bool flag = disposing && this.components != null;
			if (flag)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x060001EB RID: 491 RVA: 0x00014F70 File Offset: 0x00013170
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Utilities.BunifuPages.BunifuAnimatorNS.Animation animation = new global::Utilities.BunifuPages.BunifuAnimatorNS.Animation();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ToolRegFB.frmLoginUser));
			global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new global::Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			this.bunifuPages1 = new global::Bunifu.UI.WinForms.BunifuPages();
			this.tabPage1 = new global::System.Windows.Forms.TabPage();
			this.chkRememe = new global::Bunifu.Framework.UI.BunifuCheckbox();
			this.bunifuCustomLabel1 = new global::Bunifu.Framework.UI.BunifuCustomLabel();
			this.bunifuSeparator2 = new global::Bunifu.UI.WinForms.BunifuSeparator();
			this.btnSigin = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.txtPassSigin = new global::Bunifu.UI.WinForms.BunifuTextBox();
			this.txtEmailSigin = new global::Bunifu.UI.WinForms.BunifuTextBox();
			this.label3 = new global::System.Windows.Forms.Label();
			this.tabPage2 = new global::System.Windows.Forms.TabPage();
			this.btnSigup = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.bunifuSeparator1 = new global::Bunifu.UI.WinForms.BunifuSeparator();
			this.txtRePass = new global::Bunifu.UI.WinForms.BunifuTextBox();
			this.txtPassword = new global::Bunifu.UI.WinForms.BunifuTextBox();
			this.txtEmail = new global::Bunifu.UI.WinForms.BunifuTextBox();
			this.txtUserName = new global::Bunifu.UI.WinForms.BunifuTextBox();
			this.label1 = new global::System.Windows.Forms.Label();
			this.btnClose = new global::System.Windows.Forms.Button();
			this.bunifuGradientPanel1 = new global::Bunifu.UI.WinForms.BunifuGradientPanel();
			this.lblVersion = new global::System.Windows.Forms.Label();
			this.label4 = new global::System.Windows.Forms.Label();
			this.btnSigin1 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.btnSignup1 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.bunifuPictureBox1 = new global::Bunifu.UI.WinForms.BunifuPictureBox();
			this.label2 = new global::System.Windows.Forms.Label();
			this.btnMinimize = new global::System.Windows.Forms.Button();
			this.panel1 = new global::System.Windows.Forms.Panel();
			this.bunifuDragControl1 = new global::Bunifu.Framework.UI.BunifuDragControl(this.components);
			this.bunifuDragControl2 = new global::Bunifu.Framework.UI.BunifuDragControl(this.components);
			this.btnNapXu = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.bunifuPages1.SuspendLayout();
			this.tabPage1.SuspendLayout();
			this.tabPage2.SuspendLayout();
			this.bunifuGradientPanel1.SuspendLayout();
			this.bunifuPictureBox1.BeginInit();
			this.panel1.SuspendLayout();
			base.SuspendLayout();
			this.bunifuPages1.Alignment = global::System.Windows.Forms.TabAlignment.Bottom;
			this.bunifuPages1.AllowTransitions = true;
			this.bunifuPages1.Controls.Add(this.tabPage1);
			this.bunifuPages1.Controls.Add(this.tabPage2);
			this.bunifuPages1.Location = new global::System.Drawing.Point(322, 46);
			this.bunifuPages1.Multiline = true;
			this.bunifuPages1.Name = "bunifuPages1";
			this.bunifuPages1.Page = this.tabPage1;
			this.bunifuPages1.PageIndex = 0;
			this.bunifuPages1.PageName = "tabPage1";
			this.bunifuPages1.PageTitle = "sign_in";
			this.bunifuPages1.SelectedIndex = 0;
			this.bunifuPages1.Size = new global::System.Drawing.Size(631, 507);
			this.bunifuPages1.TabIndex = 12;
			animation.AnimateOnlyDifferences = true;
			animation.BlindCoeff = (global::System.Drawing.PointF)componentResourceManager.GetObject("animation1.BlindCoeff");
			animation.LeafCoeff = 0f;
			animation.MaxTime = 1f;
			animation.MinTime = 0f;
			animation.MosaicCoeff = (global::System.Drawing.PointF)componentResourceManager.GetObject("animation1.MosaicCoeff");
			animation.MosaicShift = (global::System.Drawing.PointF)componentResourceManager.GetObject("animation1.MosaicShift");
			animation.MosaicSize = 0;
			animation.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 0);
			animation.RotateCoeff = 0f;
			animation.RotateLimit = 0f;
			animation.ScaleCoeff = (global::System.Drawing.PointF)componentResourceManager.GetObject("animation1.ScaleCoeff");
			animation.SlideCoeff = (global::System.Drawing.PointF)componentResourceManager.GetObject("animation1.SlideCoeff");
			animation.TimeCoeff = 0f;
			animation.TransparencyCoeff = 1f;
			this.bunifuPages1.Transition = animation;
			this.bunifuPages1.TransitionType = 8;
			this.tabPage1.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.tabPage1.Controls.Add(this.chkRememe);
			this.tabPage1.Controls.Add(this.bunifuCustomLabel1);
			this.tabPage1.Controls.Add(this.bunifuSeparator2);
			this.tabPage1.Controls.Add(this.btnSigin);
			this.tabPage1.Controls.Add(this.txtPassSigin);
			this.tabPage1.Controls.Add(this.txtEmailSigin);
			this.tabPage1.Controls.Add(this.label3);
			this.tabPage1.Location = new global::System.Drawing.Point(4, 4);
			this.tabPage1.Name = "tabPage1";
			this.tabPage1.Padding = new global::System.Windows.Forms.Padding(3);
			this.tabPage1.Size = new global::System.Drawing.Size(623, 478);
			this.tabPage1.TabIndex = 0;
			this.tabPage1.Text = "sign_in";
			this.chkRememe.BackColor = global::System.Drawing.Color.FromArgb(51, 205, 117);
			this.chkRememe.ChechedOffColor = global::System.Drawing.Color.FromArgb(132, 135, 140);
			this.chkRememe.Checked = true;
			this.chkRememe.CheckedOnColor = global::System.Drawing.Color.FromArgb(51, 205, 117);
			this.chkRememe.ForeColor = global::System.Drawing.Color.White;
			this.chkRememe.Location = new global::System.Drawing.Point(109, 264);
			this.chkRememe.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.chkRememe.Name = "chkRememe";
			this.chkRememe.Size = new global::System.Drawing.Size(20, 20);
			this.chkRememe.TabIndex = 8;
			this.chkRememe.OnChange += new global::System.EventHandler(this.chkRememe_OnChange);
			this.bunifuCustomLabel1.AutoSize = true;
			this.bunifuCustomLabel1.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.bunifuCustomLabel1.ForeColor = global::System.Drawing.Color.FromArgb(24, 30, 54);
			this.bunifuCustomLabel1.Location = new global::System.Drawing.Point(137, 265);
			this.bunifuCustomLabel1.Name = "bunifuCustomLabel1";
			this.bunifuCustomLabel1.Size = new global::System.Drawing.Size(131, 20);
			this.bunifuCustomLabel1.TabIndex = 7;
			this.bunifuCustomLabel1.Text = "Ghi nhớ tài khoản";
			this.bunifuSeparator2.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuSeparator2.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuSeparator2.BackgroundImage");
			this.bunifuSeparator2.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuSeparator2.DashCap = 0;
			this.bunifuSeparator2.LineColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.bunifuSeparator2.LineStyle = 0;
			this.bunifuSeparator2.LineThickness = 2;
			this.bunifuSeparator2.Location = new global::System.Drawing.Point(223, 105);
			this.bunifuSeparator2.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuSeparator2.Name = "bunifuSeparator2";
			this.bunifuSeparator2.Orientation = 1;
			this.bunifuSeparator2.Size = new global::System.Drawing.Size(191, 10);
			this.bunifuSeparator2.TabIndex = 5;
			this.btnSigin.AllowAnimations = true;
			this.btnSigin.AllowMouseEffects = true;
			this.btnSigin.AllowToggling = false;
			this.btnSigin.AnimationSpeed = 200;
			this.btnSigin.AutoGenerateColors = false;
			this.btnSigin.AutoRoundBorders = false;
			this.btnSigin.AutoSizeLeftIcon = true;
			this.btnSigin.AutoSizeRightIcon = true;
			this.btnSigin.BackColor = global::System.Drawing.Color.Transparent;
			this.btnSigin.BackColor1 = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSigin.BackgroundImage");
			this.btnSigin.BorderStyle = 0;
			this.btnSigin.ButtonText = "Đăng nhập";
			this.btnSigin.ButtonTextMarginLeft = 0;
			this.btnSigin.ColorContrastOnClick = 45;
			this.btnSigin.ColorContrastOnHover = 45;
			this.btnSigin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			borderEdges.BottomLeft = true;
			borderEdges.BottomRight = true;
			borderEdges.TopLeft = true;
			borderEdges.TopRight = true;
			this.btnSigin.CustomizableEdges = borderEdges;
			this.btnSigin.DialogResult = global::System.Windows.Forms.DialogResult.None;
			this.btnSigin.DisabledBorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSigin.DisabledFillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSigin.DisabledForecolor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSigin.FocusState = 2;
			this.btnSigin.Font = new global::System.Drawing.Font("Segoe UI Semibold", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSigin.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin.IconLeftAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnSigin.IconLeftCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSigin.IconLeftPadding = new global::System.Windows.Forms.Padding(11, 3, 3, 3);
			this.btnSigin.IconMarginLeft = 11;
			this.btnSigin.IconPadding = 10;
			this.btnSigin.IconRightAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnSigin.IconRightCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSigin.IconRightPadding = new global::System.Windows.Forms.Padding(3, 3, 7, 3);
			this.btnSigin.IconSize = 25;
			this.btnSigin.IdleBorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.IdleBorderRadius = 35;
			this.btnSigin.IdleBorderThickness = 2;
			this.btnSigin.IdleFillColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.IdleIconLeftImage = null;
			this.btnSigin.IdleIconRightImage = null;
			this.btnSigin.IndicateFocus = false;
			this.btnSigin.Location = new global::System.Drawing.Point(417, 288);
			this.btnSigin.Name = "btnSigin";
			this.btnSigin.OnDisabledState.BorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSigin.OnDisabledState.BorderRadius = 35;
			this.btnSigin.OnDisabledState.BorderStyle = 0;
			this.btnSigin.OnDisabledState.BorderThickness = 2;
			this.btnSigin.OnDisabledState.FillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSigin.OnDisabledState.ForeColor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSigin.OnDisabledState.IconLeftImage = null;
			this.btnSigin.OnDisabledState.IconRightImage = null;
			this.btnSigin.onHoverState.BorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.onHoverState.BorderRadius = 35;
			this.btnSigin.onHoverState.BorderStyle = 0;
			this.btnSigin.onHoverState.BorderThickness = 2;
			this.btnSigin.onHoverState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin.onHoverState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.onHoverState.IconLeftImage = null;
			this.btnSigin.onHoverState.IconRightImage = null;
			this.btnSigin.OnIdleState.BorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.OnIdleState.BorderRadius = 35;
			this.btnSigin.OnIdleState.BorderStyle = 0;
			this.btnSigin.OnIdleState.BorderThickness = 2;
			this.btnSigin.OnIdleState.FillColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.OnIdleState.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin.OnIdleState.IconLeftImage = null;
			this.btnSigin.OnIdleState.IconRightImage = null;
			this.btnSigin.OnPressedState.BorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.OnPressedState.BorderRadius = 35;
			this.btnSigin.OnPressedState.BorderStyle = 0;
			this.btnSigin.OnPressedState.BorderThickness = 2;
			this.btnSigin.OnPressedState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin.OnPressedState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin.OnPressedState.IconLeftImage = null;
			this.btnSigin.OnPressedState.IconRightImage = null;
			this.btnSigin.Size = new global::System.Drawing.Size(131, 49);
			this.btnSigin.TabIndex = 4;
			this.btnSigin.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.btnSigin.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.btnSigin.TextMarginLeft = 0;
			this.btnSigin.TextPadding = new global::System.Windows.Forms.Padding(0);
			this.btnSigin.UseDefaultRadiusAndThickness = true;
			this.btnSigin.Click += new global::System.EventHandler(this.btnSigin_Click);
			this.txtPassSigin.AcceptsReturn = false;
			this.txtPassSigin.AcceptsTab = false;
			this.txtPassSigin.AnimationSpeed = 200;
			this.txtPassSigin.AutoCompleteMode = global::System.Windows.Forms.AutoCompleteMode.None;
			this.txtPassSigin.AutoCompleteSource = global::System.Windows.Forms.AutoCompleteSource.None;
			this.txtPassSigin.AutoSizeHeight = true;
			this.txtPassSigin.BackColor = global::System.Drawing.Color.Transparent;
			this.txtPassSigin.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txtPassSigin.BackgroundImage");
			this.txtPassSigin.BorderColorActive = global::System.Drawing.Color.DodgerBlue;
			this.txtPassSigin.BorderColorDisabled = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.txtPassSigin.BorderColorHover = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.txtPassSigin.BorderColorIdle = global::System.Drawing.Color.Silver;
			this.txtPassSigin.BorderRadius = 1;
			this.txtPassSigin.BorderThickness = 1;
			this.txtPassSigin.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Normal;
			this.txtPassSigin.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtPassSigin.DefaultFont = new global::System.Drawing.Font("Segoe UI", 9.25f);
			this.txtPassSigin.DefaultText = "";
			this.txtPassSigin.FillColor = global::System.Drawing.Color.White;
			this.txtPassSigin.ForeColor = global::System.Drawing.Color.Black;
			this.txtPassSigin.HideSelection = true;
			this.txtPassSigin.IconLeft = global::ToolRegFB.Properties.Resources.icons8_password_20;
			this.txtPassSigin.IconLeftCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtPassSigin.IconPadding = 11;
			this.txtPassSigin.IconRight = null;
			this.txtPassSigin.IconRightCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtPassSigin.Lines = new string[0];
			this.txtPassSigin.Location = new global::System.Drawing.Point(109, 214);
			this.txtPassSigin.MaxLength = 32767;
			this.txtPassSigin.MinimumSize = new global::System.Drawing.Size(1, 1);
			this.txtPassSigin.Modified = false;
			this.txtPassSigin.Multiline = false;
			this.txtPassSigin.Name = "txtPassSigin";
			stateProperties.BorderColor = global::System.Drawing.Color.DodgerBlue;
			stateProperties.FillColor = global::System.Drawing.Color.Empty;
			stateProperties.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtPassSigin.OnActiveState = stateProperties;
			stateProperties2.BorderColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			stateProperties2.FillColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			stateProperties2.ForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			stateProperties2.PlaceholderForeColor = global::System.Drawing.Color.DarkGray;
			this.txtPassSigin.OnDisabledState = stateProperties2;
			stateProperties3.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			stateProperties3.FillColor = global::System.Drawing.Color.Empty;
			stateProperties3.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties3.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtPassSigin.OnHoverState = stateProperties3;
			stateProperties4.BorderColor = global::System.Drawing.Color.Silver;
			stateProperties4.FillColor = global::System.Drawing.Color.White;
			stateProperties4.ForeColor = global::System.Drawing.Color.Black;
			stateProperties4.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtPassSigin.OnIdleState = stateProperties4;
			this.txtPassSigin.Padding = new global::System.Windows.Forms.Padding(3);
			this.txtPassSigin.PasswordChar = '●';
			this.txtPassSigin.PlaceholderForeColor = global::System.Drawing.Color.Silver;
			this.txtPassSigin.PlaceholderText = "Mật khẩu";
			this.txtPassSigin.ReadOnly = false;
			this.txtPassSigin.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.txtPassSigin.SelectedText = "";
			this.txtPassSigin.SelectionLength = 0;
			this.txtPassSigin.SelectionStart = 0;
			this.txtPassSigin.ShortcutsEnabled = true;
			this.txtPassSigin.Size = new global::System.Drawing.Size(439, 43);
			this.txtPassSigin.Style = 0;
			this.txtPassSigin.TabIndex = 3;
			this.txtPassSigin.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.txtPassSigin.TextMarginBottom = 0;
			this.txtPassSigin.TextMarginLeft = 3;
			this.txtPassSigin.TextMarginTop = 1;
			this.txtPassSigin.TextPlaceholder = "Mật khẩu";
			this.txtPassSigin.UseSystemPasswordChar = true;
			this.txtPassSigin.WordWrap = true;
			this.txtPassSigin.KeyPress += new global::System.Windows.Forms.KeyPressEventHandler(this.txtPassSigin_KeyPress);
			this.txtEmailSigin.AcceptsReturn = false;
			this.txtEmailSigin.AcceptsTab = false;
			this.txtEmailSigin.AnimationSpeed = 200;
			this.txtEmailSigin.AutoCompleteMode = global::System.Windows.Forms.AutoCompleteMode.None;
			this.txtEmailSigin.AutoCompleteSource = global::System.Windows.Forms.AutoCompleteSource.None;
			this.txtEmailSigin.AutoSizeHeight = true;
			this.txtEmailSigin.BackColor = global::System.Drawing.Color.Transparent;
			this.txtEmailSigin.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txtEmailSigin.BackgroundImage");
			this.txtEmailSigin.BorderColorActive = global::System.Drawing.Color.DodgerBlue;
			this.txtEmailSigin.BorderColorDisabled = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.txtEmailSigin.BorderColorHover = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.txtEmailSigin.BorderColorIdle = global::System.Drawing.Color.Silver;
			this.txtEmailSigin.BorderRadius = 1;
			this.txtEmailSigin.BorderThickness = 1;
			this.txtEmailSigin.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Normal;
			this.txtEmailSigin.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtEmailSigin.DefaultFont = new global::System.Drawing.Font("Segoe UI", 9.25f);
			this.txtEmailSigin.DefaultText = "";
			this.txtEmailSigin.FillColor = global::System.Drawing.Color.White;
			this.txtEmailSigin.ForeColor = global::System.Drawing.Color.Black;
			this.txtEmailSigin.HideSelection = true;
			this.txtEmailSigin.IconLeft = global::ToolRegFB.Properties.Resources.icons8_email_20;
			this.txtEmailSigin.IconLeftCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtEmailSigin.IconPadding = 11;
			this.txtEmailSigin.IconRight = null;
			this.txtEmailSigin.IconRightCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtEmailSigin.Lines = new string[0];
			this.txtEmailSigin.Location = new global::System.Drawing.Point(109, 154);
			this.txtEmailSigin.MaxLength = 32767;
			this.txtEmailSigin.MinimumSize = new global::System.Drawing.Size(1, 1);
			this.txtEmailSigin.Modified = false;
			this.txtEmailSigin.Multiline = false;
			this.txtEmailSigin.Name = "txtEmailSigin";
			stateProperties5.BorderColor = global::System.Drawing.Color.DodgerBlue;
			stateProperties5.FillColor = global::System.Drawing.Color.Empty;
			stateProperties5.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties5.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtEmailSigin.OnActiveState = stateProperties5;
			stateProperties6.BorderColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			stateProperties6.FillColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			stateProperties6.ForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			stateProperties6.PlaceholderForeColor = global::System.Drawing.Color.DarkGray;
			this.txtEmailSigin.OnDisabledState = stateProperties6;
			stateProperties7.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			stateProperties7.FillColor = global::System.Drawing.Color.Empty;
			stateProperties7.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties7.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtEmailSigin.OnHoverState = stateProperties7;
			stateProperties8.BorderColor = global::System.Drawing.Color.Silver;
			stateProperties8.FillColor = global::System.Drawing.Color.White;
			stateProperties8.ForeColor = global::System.Drawing.Color.Black;
			stateProperties8.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtEmailSigin.OnIdleState = stateProperties8;
			this.txtEmailSigin.Padding = new global::System.Windows.Forms.Padding(3);
			this.txtEmailSigin.PasswordChar = '\0';
			this.txtEmailSigin.PlaceholderForeColor = global::System.Drawing.Color.Silver;
			this.txtEmailSigin.PlaceholderText = "Email";
			this.txtEmailSigin.ReadOnly = false;
			this.txtEmailSigin.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.txtEmailSigin.SelectedText = "";
			this.txtEmailSigin.SelectionLength = 0;
			this.txtEmailSigin.SelectionStart = 0;
			this.txtEmailSigin.ShortcutsEnabled = true;
			this.txtEmailSigin.Size = new global::System.Drawing.Size(439, 43);
			this.txtEmailSigin.Style = 0;
			this.txtEmailSigin.TabIndex = 2;
			this.txtEmailSigin.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.txtEmailSigin.TextMarginBottom = 0;
			this.txtEmailSigin.TextMarginLeft = 3;
			this.txtEmailSigin.TextMarginTop = 1;
			this.txtEmailSigin.TextPlaceholder = "Email";
			this.txtEmailSigin.UseSystemPasswordChar = false;
			this.txtEmailSigin.WordWrap = true;
			this.txtEmailSigin.KeyPress += new global::System.Windows.Forms.KeyPressEventHandler(this.txtEmailSigin_KeyPress);
			this.label3.BackColor = global::System.Drawing.Color.Transparent;
			this.label3.Font = new global::System.Drawing.Font("Segoe UI Semibold", 25.8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.label3.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.label3.Location = new global::System.Drawing.Point(198, 39);
			this.label3.Name = "label3";
			this.label3.Size = new global::System.Drawing.Size(314, 76);
			this.label3.TabIndex = 3;
			this.label3.Text = "Đăng nhập";
			this.tabPage2.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.tabPage2.Controls.Add(this.btnSigup);
			this.tabPage2.Controls.Add(this.bunifuSeparator1);
			this.tabPage2.Controls.Add(this.txtRePass);
			this.tabPage2.Controls.Add(this.txtPassword);
			this.tabPage2.Controls.Add(this.txtEmail);
			this.tabPage2.Controls.Add(this.txtUserName);
			this.tabPage2.Controls.Add(this.label1);
			this.tabPage2.Location = new global::System.Drawing.Point(4, 4);
			this.tabPage2.Name = "tabPage2";
			this.tabPage2.Padding = new global::System.Windows.Forms.Padding(3);
			this.tabPage2.Size = new global::System.Drawing.Size(623, 478);
			this.tabPage2.TabIndex = 1;
			this.tabPage2.Text = "sign_up";
			this.btnSigup.AllowAnimations = true;
			this.btnSigup.AllowMouseEffects = true;
			this.btnSigup.AllowToggling = false;
			this.btnSigup.AnimationSpeed = 200;
			this.btnSigup.AutoGenerateColors = false;
			this.btnSigup.AutoRoundBorders = false;
			this.btnSigup.AutoSizeLeftIcon = true;
			this.btnSigup.AutoSizeRightIcon = true;
			this.btnSigup.BackColor = global::System.Drawing.Color.Transparent;
			this.btnSigup.BackColor1 = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSigup.BackgroundImage");
			this.btnSigup.BorderStyle = 0;
			this.btnSigup.ButtonText = "Đăng ký";
			this.btnSigup.ButtonTextMarginLeft = 0;
			this.btnSigup.ColorContrastOnClick = 45;
			this.btnSigup.ColorContrastOnHover = 45;
			this.btnSigup.Cursor = global::System.Windows.Forms.Cursors.Hand;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			this.btnSigup.CustomizableEdges = borderEdges2;
			this.btnSigup.DialogResult = global::System.Windows.Forms.DialogResult.None;
			this.btnSigup.DisabledBorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSigup.DisabledFillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSigup.DisabledForecolor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSigup.FocusState = 2;
			this.btnSigup.Font = new global::System.Drawing.Font("Segoe UI Semibold", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSigup.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigup.IconLeftAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnSigup.IconLeftCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSigup.IconLeftPadding = new global::System.Windows.Forms.Padding(11, 3, 3, 3);
			this.btnSigup.IconMarginLeft = 11;
			this.btnSigup.IconPadding = 10;
			this.btnSigup.IconRightAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnSigup.IconRightCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSigup.IconRightPadding = new global::System.Windows.Forms.Padding(3, 3, 7, 3);
			this.btnSigup.IconSize = 25;
			this.btnSigup.IdleBorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.IdleBorderRadius = 35;
			this.btnSigup.IdleBorderThickness = 2;
			this.btnSigup.IdleFillColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.IdleIconLeftImage = null;
			this.btnSigup.IdleIconRightImage = null;
			this.btnSigup.IndicateFocus = false;
			this.btnSigup.Location = new global::System.Drawing.Point(407, 333);
			this.btnSigup.Name = "btnSigup";
			this.btnSigup.OnDisabledState.BorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSigup.OnDisabledState.BorderRadius = 35;
			this.btnSigup.OnDisabledState.BorderStyle = 0;
			this.btnSigup.OnDisabledState.BorderThickness = 2;
			this.btnSigup.OnDisabledState.FillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSigup.OnDisabledState.ForeColor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSigup.OnDisabledState.IconLeftImage = null;
			this.btnSigup.OnDisabledState.IconRightImage = null;
			this.btnSigup.onHoverState.BorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.onHoverState.BorderRadius = 35;
			this.btnSigup.onHoverState.BorderStyle = 0;
			this.btnSigup.onHoverState.BorderThickness = 2;
			this.btnSigup.onHoverState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigup.onHoverState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.onHoverState.IconLeftImage = null;
			this.btnSigup.onHoverState.IconRightImage = null;
			this.btnSigup.OnIdleState.BorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.OnIdleState.BorderRadius = 35;
			this.btnSigup.OnIdleState.BorderStyle = 0;
			this.btnSigup.OnIdleState.BorderThickness = 2;
			this.btnSigup.OnIdleState.FillColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.OnIdleState.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigup.OnIdleState.IconLeftImage = null;
			this.btnSigup.OnIdleState.IconRightImage = null;
			this.btnSigup.OnPressedState.BorderColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.OnPressedState.BorderRadius = 35;
			this.btnSigup.OnPressedState.BorderStyle = 0;
			this.btnSigup.OnPressedState.BorderThickness = 2;
			this.btnSigup.OnPressedState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigup.OnPressedState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigup.OnPressedState.IconLeftImage = null;
			this.btnSigup.OnPressedState.IconRightImage = null;
			this.btnSigup.Size = new global::System.Drawing.Size(131, 49);
			this.btnSigup.TabIndex = 7;
			this.btnSigup.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.btnSigup.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.btnSigup.TextMarginLeft = 0;
			this.btnSigup.TextPadding = new global::System.Windows.Forms.Padding(0);
			this.btnSigup.UseDefaultRadiusAndThickness = true;
			this.btnSigup.Click += new global::System.EventHandler(this.btnSigup_Click);
			this.bunifuSeparator1.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuSeparator1.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuSeparator1.BackgroundImage");
			this.bunifuSeparator1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuSeparator1.DashCap = 0;
			this.bunifuSeparator1.LineColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.bunifuSeparator1.LineStyle = 0;
			this.bunifuSeparator1.LineThickness = 2;
			this.bunifuSeparator1.Location = new global::System.Drawing.Point(221, 94);
			this.bunifuSeparator1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuSeparator1.Name = "bunifuSeparator1";
			this.bunifuSeparator1.Orientation = 1;
			this.bunifuSeparator1.Size = new global::System.Drawing.Size(191, 10);
			this.bunifuSeparator1.TabIndex = 2;
			this.txtRePass.AcceptsReturn = false;
			this.txtRePass.AcceptsTab = false;
			this.txtRePass.AnimationSpeed = 200;
			this.txtRePass.AutoCompleteMode = global::System.Windows.Forms.AutoCompleteMode.None;
			this.txtRePass.AutoCompleteSource = global::System.Windows.Forms.AutoCompleteSource.None;
			this.txtRePass.AutoSizeHeight = true;
			this.txtRePass.BackColor = global::System.Drawing.Color.Transparent;
			this.txtRePass.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txtRePass.BackgroundImage");
			this.txtRePass.BorderColorActive = global::System.Drawing.Color.DodgerBlue;
			this.txtRePass.BorderColorDisabled = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.txtRePass.BorderColorHover = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.txtRePass.BorderColorIdle = global::System.Drawing.Color.Silver;
			this.txtRePass.BorderRadius = 1;
			this.txtRePass.BorderThickness = 1;
			this.txtRePass.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Normal;
			this.txtRePass.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtRePass.DefaultFont = new global::System.Drawing.Font("Segoe UI", 9.25f);
			this.txtRePass.DefaultText = "";
			this.txtRePass.FillColor = global::System.Drawing.Color.White;
			this.txtRePass.ForeColor = global::System.Drawing.Color.Black;
			this.txtRePass.HideSelection = true;
			this.txtRePass.IconLeft = global::ToolRegFB.Properties.Resources.icons8_password_20;
			this.txtRePass.IconLeftCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtRePass.IconPadding = 11;
			this.txtRePass.IconRight = null;
			this.txtRePass.IconRightCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtRePass.Lines = new string[0];
			this.txtRePass.Location = new global::System.Drawing.Point(99, 272);
			this.txtRePass.MaxLength = 32767;
			this.txtRePass.MinimumSize = new global::System.Drawing.Size(1, 1);
			this.txtRePass.Modified = false;
			this.txtRePass.Multiline = false;
			this.txtRePass.Name = "txtRePass";
			stateProperties9.BorderColor = global::System.Drawing.Color.DodgerBlue;
			stateProperties9.FillColor = global::System.Drawing.Color.Empty;
			stateProperties9.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties9.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtRePass.OnActiveState = stateProperties9;
			stateProperties10.BorderColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			stateProperties10.FillColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			stateProperties10.ForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			stateProperties10.PlaceholderForeColor = global::System.Drawing.Color.DarkGray;
			this.txtRePass.OnDisabledState = stateProperties10;
			stateProperties11.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			stateProperties11.FillColor = global::System.Drawing.Color.Empty;
			stateProperties11.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties11.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtRePass.OnHoverState = stateProperties11;
			stateProperties12.BorderColor = global::System.Drawing.Color.Silver;
			stateProperties12.FillColor = global::System.Drawing.Color.White;
			stateProperties12.ForeColor = global::System.Drawing.Color.Black;
			stateProperties12.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtRePass.OnIdleState = stateProperties12;
			this.txtRePass.Padding = new global::System.Windows.Forms.Padding(3);
			this.txtRePass.PasswordChar = '●';
			this.txtRePass.PlaceholderForeColor = global::System.Drawing.Color.Silver;
			this.txtRePass.PlaceholderText = "Nhập lại mật khẩu";
			this.txtRePass.ReadOnly = false;
			this.txtRePass.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.txtRePass.SelectedText = "";
			this.txtRePass.SelectionLength = 0;
			this.txtRePass.SelectionStart = 0;
			this.txtRePass.ShortcutsEnabled = true;
			this.txtRePass.Size = new global::System.Drawing.Size(439, 43);
			this.txtRePass.Style = 0;
			this.txtRePass.TabIndex = 6;
			this.txtRePass.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.txtRePass.TextMarginBottom = 0;
			this.txtRePass.TextMarginLeft = 3;
			this.txtRePass.TextMarginTop = 1;
			this.txtRePass.TextPlaceholder = "Nhập lại mật khẩu";
			this.txtRePass.UseSystemPasswordChar = true;
			this.txtRePass.WordWrap = true;
			this.txtPassword.AcceptsReturn = false;
			this.txtPassword.AcceptsTab = false;
			this.txtPassword.AnimationSpeed = 200;
			this.txtPassword.AutoCompleteMode = global::System.Windows.Forms.AutoCompleteMode.None;
			this.txtPassword.AutoCompleteSource = global::System.Windows.Forms.AutoCompleteSource.None;
			this.txtPassword.AutoSizeHeight = true;
			this.txtPassword.BackColor = global::System.Drawing.Color.Transparent;
			this.txtPassword.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txtPassword.BackgroundImage");
			this.txtPassword.BorderColorActive = global::System.Drawing.Color.DodgerBlue;
			this.txtPassword.BorderColorDisabled = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.txtPassword.BorderColorHover = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.txtPassword.BorderColorIdle = global::System.Drawing.Color.Silver;
			this.txtPassword.BorderRadius = 1;
			this.txtPassword.BorderThickness = 1;
			this.txtPassword.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Normal;
			this.txtPassword.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtPassword.DefaultFont = new global::System.Drawing.Font("Segoe UI", 9.25f);
			this.txtPassword.DefaultText = "";
			this.txtPassword.FillColor = global::System.Drawing.Color.White;
			this.txtPassword.ForeColor = global::System.Drawing.Color.Black;
			this.txtPassword.HideSelection = true;
			this.txtPassword.IconLeft = global::ToolRegFB.Properties.Resources.icons8_password_20;
			this.txtPassword.IconLeftCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtPassword.IconPadding = 11;
			this.txtPassword.IconRight = null;
			this.txtPassword.IconRightCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtPassword.Lines = new string[0];
			this.txtPassword.Location = new global::System.Drawing.Point(99, 223);
			this.txtPassword.MaxLength = 32767;
			this.txtPassword.MinimumSize = new global::System.Drawing.Size(1, 1);
			this.txtPassword.Modified = false;
			this.txtPassword.Multiline = false;
			this.txtPassword.Name = "txtPassword";
			stateProperties13.BorderColor = global::System.Drawing.Color.DodgerBlue;
			stateProperties13.FillColor = global::System.Drawing.Color.Empty;
			stateProperties13.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties13.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtPassword.OnActiveState = stateProperties13;
			stateProperties14.BorderColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			stateProperties14.FillColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			stateProperties14.ForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			stateProperties14.PlaceholderForeColor = global::System.Drawing.Color.DarkGray;
			this.txtPassword.OnDisabledState = stateProperties14;
			stateProperties15.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			stateProperties15.FillColor = global::System.Drawing.Color.Empty;
			stateProperties15.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties15.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtPassword.OnHoverState = stateProperties15;
			stateProperties16.BorderColor = global::System.Drawing.Color.Silver;
			stateProperties16.FillColor = global::System.Drawing.Color.White;
			stateProperties16.ForeColor = global::System.Drawing.Color.Black;
			stateProperties16.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtPassword.OnIdleState = stateProperties16;
			this.txtPassword.Padding = new global::System.Windows.Forms.Padding(3);
			this.txtPassword.PasswordChar = '●';
			this.txtPassword.PlaceholderForeColor = global::System.Drawing.Color.Silver;
			this.txtPassword.PlaceholderText = "Mật khẩu";
			this.txtPassword.ReadOnly = false;
			this.txtPassword.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.txtPassword.SelectedText = "";
			this.txtPassword.SelectionLength = 0;
			this.txtPassword.SelectionStart = 0;
			this.txtPassword.ShortcutsEnabled = true;
			this.txtPassword.Size = new global::System.Drawing.Size(439, 43);
			this.txtPassword.Style = 0;
			this.txtPassword.TabIndex = 5;
			this.txtPassword.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.txtPassword.TextMarginBottom = 0;
			this.txtPassword.TextMarginLeft = 3;
			this.txtPassword.TextMarginTop = 1;
			this.txtPassword.TextPlaceholder = "Mật khẩu";
			this.txtPassword.UseSystemPasswordChar = true;
			this.txtPassword.WordWrap = true;
			this.txtEmail.AcceptsReturn = false;
			this.txtEmail.AcceptsTab = false;
			this.txtEmail.AnimationSpeed = 200;
			this.txtEmail.AutoCompleteMode = global::System.Windows.Forms.AutoCompleteMode.None;
			this.txtEmail.AutoCompleteSource = global::System.Windows.Forms.AutoCompleteSource.None;
			this.txtEmail.AutoSizeHeight = true;
			this.txtEmail.BackColor = global::System.Drawing.Color.Transparent;
			this.txtEmail.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txtEmail.BackgroundImage");
			this.txtEmail.BorderColorActive = global::System.Drawing.Color.DodgerBlue;
			this.txtEmail.BorderColorDisabled = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.txtEmail.BorderColorHover = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.txtEmail.BorderColorIdle = global::System.Drawing.Color.Silver;
			this.txtEmail.BorderRadius = 1;
			this.txtEmail.BorderThickness = 1;
			this.txtEmail.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Normal;
			this.txtEmail.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtEmail.DefaultFont = new global::System.Drawing.Font("Segoe UI", 9.25f);
			this.txtEmail.DefaultText = "";
			this.txtEmail.FillColor = global::System.Drawing.Color.White;
			this.txtEmail.ForeColor = global::System.Drawing.Color.Black;
			this.txtEmail.HideSelection = true;
			this.txtEmail.IconLeft = global::ToolRegFB.Properties.Resources.icons8_email_20;
			this.txtEmail.IconLeftCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtEmail.IconPadding = 11;
			this.txtEmail.IconRight = null;
			this.txtEmail.IconRightCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtEmail.Lines = new string[0];
			this.txtEmail.Location = new global::System.Drawing.Point(99, 174);
			this.txtEmail.MaxLength = 32767;
			this.txtEmail.MinimumSize = new global::System.Drawing.Size(1, 1);
			this.txtEmail.Modified = false;
			this.txtEmail.Multiline = false;
			this.txtEmail.Name = "txtEmail";
			stateProperties17.BorderColor = global::System.Drawing.Color.DodgerBlue;
			stateProperties17.FillColor = global::System.Drawing.Color.Empty;
			stateProperties17.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties17.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtEmail.OnActiveState = stateProperties17;
			stateProperties18.BorderColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			stateProperties18.FillColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			stateProperties18.ForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			stateProperties18.PlaceholderForeColor = global::System.Drawing.Color.DarkGray;
			this.txtEmail.OnDisabledState = stateProperties18;
			stateProperties19.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			stateProperties19.FillColor = global::System.Drawing.Color.Empty;
			stateProperties19.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties19.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtEmail.OnHoverState = stateProperties19;
			stateProperties20.BorderColor = global::System.Drawing.Color.Silver;
			stateProperties20.FillColor = global::System.Drawing.Color.White;
			stateProperties20.ForeColor = global::System.Drawing.Color.Black;
			stateProperties20.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtEmail.OnIdleState = stateProperties20;
			this.txtEmail.Padding = new global::System.Windows.Forms.Padding(3);
			this.txtEmail.PasswordChar = '\0';
			this.txtEmail.PlaceholderForeColor = global::System.Drawing.Color.Silver;
			this.txtEmail.PlaceholderText = "Email";
			this.txtEmail.ReadOnly = false;
			this.txtEmail.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.txtEmail.SelectedText = "";
			this.txtEmail.SelectionLength = 0;
			this.txtEmail.SelectionStart = 0;
			this.txtEmail.ShortcutsEnabled = true;
			this.txtEmail.Size = new global::System.Drawing.Size(439, 43);
			this.txtEmail.Style = 0;
			this.txtEmail.TabIndex = 4;
			this.txtEmail.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.txtEmail.TextMarginBottom = 0;
			this.txtEmail.TextMarginLeft = 3;
			this.txtEmail.TextMarginTop = 1;
			this.txtEmail.TextPlaceholder = "Email";
			this.txtEmail.UseSystemPasswordChar = false;
			this.txtEmail.WordWrap = true;
			this.txtUserName.AcceptsReturn = false;
			this.txtUserName.AcceptsTab = false;
			this.txtUserName.AnimationSpeed = 200;
			this.txtUserName.AutoCompleteMode = global::System.Windows.Forms.AutoCompleteMode.None;
			this.txtUserName.AutoCompleteSource = global::System.Windows.Forms.AutoCompleteSource.None;
			this.txtUserName.AutoSizeHeight = true;
			this.txtUserName.BackColor = global::System.Drawing.Color.Transparent;
			this.txtUserName.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txtUserName.BackgroundImage");
			this.txtUserName.BorderColorActive = global::System.Drawing.Color.DodgerBlue;
			this.txtUserName.BorderColorDisabled = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.txtUserName.BorderColorHover = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.txtUserName.BorderColorIdle = global::System.Drawing.Color.Silver;
			this.txtUserName.BorderRadius = 1;
			this.txtUserName.BorderThickness = 1;
			this.txtUserName.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Normal;
			this.txtUserName.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtUserName.DefaultFont = new global::System.Drawing.Font("Segoe UI", 9.25f);
			this.txtUserName.DefaultText = "";
			this.txtUserName.FillColor = global::System.Drawing.Color.White;
			this.txtUserName.ForeColor = global::System.Drawing.Color.Black;
			this.txtUserName.HideSelection = true;
			this.txtUserName.IconLeft = global::ToolRegFB.Properties.Resources.icons8_user_20;
			this.txtUserName.IconLeftCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtUserName.IconPadding = 11;
			this.txtUserName.IconRight = null;
			this.txtUserName.IconRightCursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtUserName.Lines = new string[0];
			this.txtUserName.Location = new global::System.Drawing.Point(99, 125);
			this.txtUserName.MaxLength = 32767;
			this.txtUserName.MinimumSize = new global::System.Drawing.Size(1, 1);
			this.txtUserName.Modified = false;
			this.txtUserName.Multiline = false;
			this.txtUserName.Name = "txtUserName";
			stateProperties21.BorderColor = global::System.Drawing.Color.DodgerBlue;
			stateProperties21.FillColor = global::System.Drawing.Color.Empty;
			stateProperties21.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties21.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtUserName.OnActiveState = stateProperties21;
			stateProperties22.BorderColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			stateProperties22.FillColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			stateProperties22.ForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			stateProperties22.PlaceholderForeColor = global::System.Drawing.Color.DarkGray;
			this.txtUserName.OnDisabledState = stateProperties22;
			stateProperties23.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			stateProperties23.FillColor = global::System.Drawing.Color.Empty;
			stateProperties23.ForeColor = global::System.Drawing.Color.Empty;
			stateProperties23.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtUserName.OnHoverState = stateProperties23;
			stateProperties24.BorderColor = global::System.Drawing.Color.Silver;
			stateProperties24.FillColor = global::System.Drawing.Color.White;
			stateProperties24.ForeColor = global::System.Drawing.Color.Black;
			stateProperties24.PlaceholderForeColor = global::System.Drawing.Color.Empty;
			this.txtUserName.OnIdleState = stateProperties24;
			this.txtUserName.Padding = new global::System.Windows.Forms.Padding(3);
			this.txtUserName.PasswordChar = '\0';
			this.txtUserName.PlaceholderForeColor = global::System.Drawing.Color.Silver;
			this.txtUserName.PlaceholderText = "Họ và tên";
			this.txtUserName.ReadOnly = false;
			this.txtUserName.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.txtUserName.SelectedText = "";
			this.txtUserName.SelectionLength = 0;
			this.txtUserName.SelectionStart = 0;
			this.txtUserName.ShortcutsEnabled = true;
			this.txtUserName.Size = new global::System.Drawing.Size(439, 43);
			this.txtUserName.Style = 0;
			this.txtUserName.TabIndex = 3;
			this.txtUserName.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.txtUserName.TextMarginBottom = 0;
			this.txtUserName.TextMarginLeft = 3;
			this.txtUserName.TextMarginTop = 1;
			this.txtUserName.TextPlaceholder = "Họ và tên";
			this.txtUserName.UseSystemPasswordChar = false;
			this.txtUserName.WordWrap = true;
			this.label1.BackColor = global::System.Drawing.Color.Transparent;
			this.label1.Font = new global::System.Drawing.Font("Segoe UI Semibold", 25.8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.label1.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.label1.Location = new global::System.Drawing.Point(165, 28);
			this.label1.Name = "label1";
			this.label1.Size = new global::System.Drawing.Size(314, 76);
			this.label1.TabIndex = 0;
			this.label1.Text = "Tạo tài khoản";
			this.btnClose.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.btnClose.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnClose.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnClose.Image = global::ToolRegFB.Properties.Resources.icons8_x_20__3_;
			this.btnClose.Location = new global::System.Drawing.Point(598, 4);
			this.btnClose.Name = "btnClose";
			this.btnClose.Size = new global::System.Drawing.Size(37, 36);
			this.btnClose.TabIndex = 9;
			this.btnClose.Text = "button1";
			this.btnClose.UseVisualStyleBackColor = true;
			this.btnClose.Click += new global::System.EventHandler(this.btnClose_Click);
			this.bunifuGradientPanel1.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuGradientPanel1.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuGradientPanel1.BackgroundImage");
			this.bunifuGradientPanel1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuGradientPanel1.BorderRadius = 1;
			this.bunifuGradientPanel1.Controls.Add(this.lblVersion);
			this.bunifuGradientPanel1.Controls.Add(this.label4);
			this.bunifuGradientPanel1.Controls.Add(this.btnNapXu);
			this.bunifuGradientPanel1.Controls.Add(this.btnSigin1);
			this.bunifuGradientPanel1.Controls.Add(this.btnSignup1);
			this.bunifuGradientPanel1.Controls.Add(this.bunifuPictureBox1);
			this.bunifuGradientPanel1.Controls.Add(this.label2);
			this.bunifuGradientPanel1.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.bunifuGradientPanel1.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.bunifuGradientPanel1.GradientBottomLeft = global::System.Drawing.Color.FromArgb(24, 30, 54);
			this.bunifuGradientPanel1.GradientBottomRight = global::System.Drawing.Color.FromArgb(24, 30, 54);
			this.bunifuGradientPanel1.GradientTopLeft = global::System.Drawing.Color.FromArgb(24, 30, 54);
			this.bunifuGradientPanel1.GradientTopRight = global::System.Drawing.Color.FromArgb(24, 30, 54);
			this.bunifuGradientPanel1.Location = new global::System.Drawing.Point(0, 0);
			this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
			this.bunifuGradientPanel1.Quality = 10;
			this.bunifuGradientPanel1.Size = new global::System.Drawing.Size(316, 565);
			this.bunifuGradientPanel1.TabIndex = 0;
			this.lblVersion.AutoSize = true;
			this.lblVersion.Font = new global::System.Drawing.Font("Segoe UI", 10.8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblVersion.ForeColor = global::System.Drawing.Color.FromArgb(245, 81, 66);
			this.lblVersion.Location = new global::System.Drawing.Point(162, 410);
			this.lblVersion.Name = "lblVersion";
			this.lblVersion.Size = new global::System.Drawing.Size(55, 25);
			this.lblVersion.TabIndex = 11;
			this.lblVersion.Text = "1.0.0";
			this.label4.AutoSize = true;
			this.label4.Font = new global::System.Drawing.Font("Segoe UI Semibold", 10.8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.label4.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.label4.Location = new global::System.Drawing.Point(76, 410);
			this.label4.Name = "label4";
			this.label4.Size = new global::System.Drawing.Size(80, 25);
			this.label4.TabIndex = 11;
			this.label4.Text = "Version:";
			this.btnSigin1.AllowAnimations = true;
			this.btnSigin1.AllowMouseEffects = true;
			this.btnSigin1.AllowToggling = false;
			this.btnSigin1.AnimationSpeed = 200;
			this.btnSigin1.AutoGenerateColors = false;
			this.btnSigin1.AutoRoundBorders = false;
			this.btnSigin1.AutoSizeLeftIcon = true;
			this.btnSigin1.AutoSizeRightIcon = true;
			this.btnSigin1.BackColor = global::System.Drawing.Color.Transparent;
			this.btnSigin1.BackColor1 = global::System.Drawing.Color.Transparent;
			this.btnSigin1.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSigin1.BackgroundImage");
			this.btnSigin1.BorderStyle = 0;
			this.btnSigin1.ButtonText = "Đăng nhập";
			this.btnSigin1.ButtonTextMarginLeft = 0;
			this.btnSigin1.ColorContrastOnClick = 45;
			this.btnSigin1.ColorContrastOnHover = 45;
			this.btnSigin1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			borderEdges3.BottomLeft = true;
			borderEdges3.BottomRight = true;
			borderEdges3.TopLeft = true;
			borderEdges3.TopRight = true;
			this.btnSigin1.CustomizableEdges = borderEdges3;
			this.btnSigin1.DialogResult = global::System.Windows.Forms.DialogResult.None;
			this.btnSigin1.DisabledBorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSigin1.DisabledFillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSigin1.DisabledForecolor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSigin1.FocusState = 2;
			this.btnSigin1.Font = new global::System.Drawing.Font("Segoe UI Semibold", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSigin1.ForeColor = global::System.Drawing.Color.White;
			this.btnSigin1.IconLeftAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnSigin1.IconLeftCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSigin1.IconLeftPadding = new global::System.Windows.Forms.Padding(11, 3, 3, 3);
			this.btnSigin1.IconMarginLeft = 11;
			this.btnSigin1.IconPadding = 10;
			this.btnSigin1.IconRightAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnSigin1.IconRightCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSigin1.IconRightPadding = new global::System.Windows.Forms.Padding(3, 3, 7, 3);
			this.btnSigin1.IconSize = 25;
			this.btnSigin1.IdleBorderColor = global::System.Drawing.Color.White;
			this.btnSigin1.IdleBorderRadius = 35;
			this.btnSigin1.IdleBorderThickness = 2;
			this.btnSigin1.IdleFillColor = global::System.Drawing.Color.Transparent;
			this.btnSigin1.IdleIconLeftImage = null;
			this.btnSigin1.IdleIconRightImage = null;
			this.btnSigin1.IndicateFocus = false;
			this.btnSigin1.Location = new global::System.Drawing.Point(24, 450);
			this.btnSigin1.Name = "btnSigin1";
			this.btnSigin1.OnDisabledState.BorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSigin1.OnDisabledState.BorderRadius = 35;
			this.btnSigin1.OnDisabledState.BorderStyle = 0;
			this.btnSigin1.OnDisabledState.BorderThickness = 2;
			this.btnSigin1.OnDisabledState.FillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSigin1.OnDisabledState.ForeColor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSigin1.OnDisabledState.IconLeftImage = null;
			this.btnSigin1.OnDisabledState.IconRightImage = null;
			this.btnSigin1.onHoverState.BorderColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin1.onHoverState.BorderRadius = 35;
			this.btnSigin1.onHoverState.BorderStyle = 0;
			this.btnSigin1.onHoverState.BorderThickness = 2;
			this.btnSigin1.onHoverState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin1.onHoverState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin1.onHoverState.IconLeftImage = null;
			this.btnSigin1.onHoverState.IconRightImage = null;
			this.btnSigin1.OnIdleState.BorderColor = global::System.Drawing.Color.White;
			this.btnSigin1.OnIdleState.BorderRadius = 35;
			this.btnSigin1.OnIdleState.BorderStyle = 0;
			this.btnSigin1.OnIdleState.BorderThickness = 2;
			this.btnSigin1.OnIdleState.FillColor = global::System.Drawing.Color.Transparent;
			this.btnSigin1.OnIdleState.ForeColor = global::System.Drawing.Color.White;
			this.btnSigin1.OnIdleState.IconLeftImage = null;
			this.btnSigin1.OnIdleState.IconRightImage = null;
			this.btnSigin1.OnPressedState.BorderColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin1.OnPressedState.BorderRadius = 35;
			this.btnSigin1.OnPressedState.BorderStyle = 0;
			this.btnSigin1.OnPressedState.BorderThickness = 2;
			this.btnSigin1.OnPressedState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSigin1.OnPressedState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSigin1.OnPressedState.IconLeftImage = null;
			this.btnSigin1.OnPressedState.IconRightImage = null;
			this.btnSigin1.Size = new global::System.Drawing.Size(131, 49);
			this.btnSigin1.TabIndex = 1;
			this.btnSigin1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.btnSigin1.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.btnSigin1.TextMarginLeft = 0;
			this.btnSigin1.TextPadding = new global::System.Windows.Forms.Padding(0);
			this.btnSigin1.UseDefaultRadiusAndThickness = true;
			this.btnSigin1.Click += new global::System.EventHandler(this.btnSigin1_Click_1);
			this.btnSignup1.AllowAnimations = true;
			this.btnSignup1.AllowMouseEffects = true;
			this.btnSignup1.AllowToggling = false;
			this.btnSignup1.AnimationSpeed = 200;
			this.btnSignup1.AutoGenerateColors = false;
			this.btnSignup1.AutoRoundBorders = false;
			this.btnSignup1.AutoSizeLeftIcon = true;
			this.btnSignup1.AutoSizeRightIcon = true;
			this.btnSignup1.BackColor = global::System.Drawing.Color.Transparent;
			this.btnSignup1.BackColor1 = global::System.Drawing.Color.Transparent;
			this.btnSignup1.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSignup1.BackgroundImage");
			this.btnSignup1.BorderStyle = 0;
			this.btnSignup1.ButtonText = "Đăng ký";
			this.btnSignup1.ButtonTextMarginLeft = 0;
			this.btnSignup1.ColorContrastOnClick = 45;
			this.btnSignup1.ColorContrastOnHover = 45;
			this.btnSignup1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			borderEdges4.BottomLeft = true;
			borderEdges4.BottomRight = true;
			borderEdges4.TopLeft = true;
			borderEdges4.TopRight = true;
			this.btnSignup1.CustomizableEdges = borderEdges4;
			this.btnSignup1.DialogResult = global::System.Windows.Forms.DialogResult.None;
			this.btnSignup1.DisabledBorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSignup1.DisabledFillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSignup1.DisabledForecolor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSignup1.FocusState = 2;
			this.btnSignup1.Font = new global::System.Drawing.Font("Segoe UI Semibold", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSignup1.ForeColor = global::System.Drawing.Color.White;
			this.btnSignup1.IconLeftAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnSignup1.IconLeftCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSignup1.IconLeftPadding = new global::System.Windows.Forms.Padding(11, 3, 3, 3);
			this.btnSignup1.IconMarginLeft = 11;
			this.btnSignup1.IconPadding = 10;
			this.btnSignup1.IconRightAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnSignup1.IconRightCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnSignup1.IconRightPadding = new global::System.Windows.Forms.Padding(3, 3, 7, 3);
			this.btnSignup1.IconSize = 25;
			this.btnSignup1.IdleBorderColor = global::System.Drawing.Color.White;
			this.btnSignup1.IdleBorderRadius = 35;
			this.btnSignup1.IdleBorderThickness = 2;
			this.btnSignup1.IdleFillColor = global::System.Drawing.Color.Transparent;
			this.btnSignup1.IdleIconLeftImage = null;
			this.btnSignup1.IdleIconRightImage = null;
			this.btnSignup1.IndicateFocus = false;
			this.btnSignup1.Location = new global::System.Drawing.Point(161, 450);
			this.btnSignup1.Name = "btnSignup1";
			this.btnSignup1.OnDisabledState.BorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnSignup1.OnDisabledState.BorderRadius = 35;
			this.btnSignup1.OnDisabledState.BorderStyle = 0;
			this.btnSignup1.OnDisabledState.BorderThickness = 2;
			this.btnSignup1.OnDisabledState.FillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnSignup1.OnDisabledState.ForeColor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnSignup1.OnDisabledState.IconLeftImage = null;
			this.btnSignup1.OnDisabledState.IconRightImage = null;
			this.btnSignup1.onHoverState.BorderColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSignup1.onHoverState.BorderRadius = 35;
			this.btnSignup1.onHoverState.BorderStyle = 0;
			this.btnSignup1.onHoverState.BorderThickness = 2;
			this.btnSignup1.onHoverState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSignup1.onHoverState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSignup1.onHoverState.IconLeftImage = null;
			this.btnSignup1.onHoverState.IconRightImage = null;
			this.btnSignup1.OnIdleState.BorderColor = global::System.Drawing.Color.White;
			this.btnSignup1.OnIdleState.BorderRadius = 35;
			this.btnSignup1.OnIdleState.BorderStyle = 0;
			this.btnSignup1.OnIdleState.BorderThickness = 2;
			this.btnSignup1.OnIdleState.FillColor = global::System.Drawing.Color.Transparent;
			this.btnSignup1.OnIdleState.ForeColor = global::System.Drawing.Color.White;
			this.btnSignup1.OnIdleState.IconLeftImage = null;
			this.btnSignup1.OnIdleState.IconRightImage = null;
			this.btnSignup1.OnPressedState.BorderColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSignup1.OnPressedState.BorderRadius = 35;
			this.btnSignup1.OnPressedState.BorderStyle = 0;
			this.btnSignup1.OnPressedState.BorderThickness = 2;
			this.btnSignup1.OnPressedState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnSignup1.OnPressedState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnSignup1.OnPressedState.IconLeftImage = null;
			this.btnSignup1.OnPressedState.IconRightImage = null;
			this.btnSignup1.Size = new global::System.Drawing.Size(131, 49);
			this.btnSignup1.TabIndex = 1;
			this.btnSignup1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.btnSignup1.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.btnSignup1.TextMarginLeft = 0;
			this.btnSignup1.TextPadding = new global::System.Windows.Forms.Padding(0);
			this.btnSignup1.UseDefaultRadiusAndThickness = true;
			this.btnSignup1.Click += new global::System.EventHandler(this.btnSignup1_Click);
			this.bunifuPictureBox1.AllowFocused = false;
			this.bunifuPictureBox1.AutoSizeHeight = true;
			this.bunifuPictureBox1.BorderRadius = 0;
			this.bunifuPictureBox1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.bunifuPictureBox1.Image = global::ToolRegFB.Properties.Resources.Publication_Facebook_940x788__px___Dimensions_personnalisées2;
			this.bunifuPictureBox1.IsCircle = true;
			this.bunifuPictureBox1.Location = new global::System.Drawing.Point(0, 0);
			this.bunifuPictureBox1.Name = "bunifuPictureBox1";
			this.bunifuPictureBox1.Size = new global::System.Drawing.Size(316, 316);
			this.bunifuPictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.bunifuPictureBox1.TabIndex = 1;
			this.bunifuPictureBox1.TabStop = false;
			this.bunifuPictureBox1.Type = 1;
			this.label2.AutoSize = true;
			this.label2.Font = new global::System.Drawing.Font("Segoe UI Semibold", 13f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.label2.Location = new global::System.Drawing.Point(4, 336);
			this.label2.Name = "label2";
			this.label2.Size = new global::System.Drawing.Size(288, 60);
			this.label2.TabIndex = 10;
			this.label2.Text = "Chào mừng mọi người đến \r\n    với Tool Social Rabbit";
			this.btnMinimize.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.btnMinimize.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnMinimize.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnMinimize.Image = global::ToolRegFB.Properties.Resources.icons8_minimize_window_25;
			this.btnMinimize.Location = new global::System.Drawing.Point(557, 4);
			this.btnMinimize.Name = "btnMinimize";
			this.btnMinimize.Size = new global::System.Drawing.Size(37, 36);
			this.btnMinimize.TabIndex = 8;
			this.btnMinimize.Text = "button1";
			this.btnMinimize.UseVisualStyleBackColor = true;
			this.btnMinimize.Click += new global::System.EventHandler(this.btnMinimize_Click);
			this.panel1.Controls.Add(this.btnMinimize);
			this.panel1.Controls.Add(this.btnClose);
			this.panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.panel1.Location = new global::System.Drawing.Point(316, 0);
			this.panel1.Name = "panel1";
			this.panel1.Size = new global::System.Drawing.Size(641, 44);
			this.panel1.TabIndex = 13;
			this.bunifuDragControl1.Fixed = true;
			this.bunifuDragControl1.Horizontal = true;
			this.bunifuDragControl1.TargetControl = this.panel1;
			this.bunifuDragControl1.Vertical = true;
			this.bunifuDragControl2.Fixed = true;
			this.bunifuDragControl2.Horizontal = true;
			this.bunifuDragControl2.TargetControl = this.panel1;
			this.bunifuDragControl2.Vertical = true;
			this.btnNapXu.AllowAnimations = true;
			this.btnNapXu.AllowMouseEffects = true;
			this.btnNapXu.AllowToggling = false;
			this.btnNapXu.AnimationSpeed = 200;
			this.btnNapXu.AutoGenerateColors = false;
			this.btnNapXu.AutoRoundBorders = false;
			this.btnNapXu.AutoSizeLeftIcon = true;
			this.btnNapXu.AutoSizeRightIcon = true;
			this.btnNapXu.BackColor = global::System.Drawing.Color.Transparent;
			this.btnNapXu.BackColor1 = global::System.Drawing.Color.Transparent;
			this.btnNapXu.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("btnNapXu.BackgroundImage");
			this.btnNapXu.BorderStyle = 0;
			this.btnNapXu.ButtonText = "Nạp xu";
			this.btnNapXu.ButtonTextMarginLeft = 0;
			this.btnNapXu.ColorContrastOnClick = 45;
			this.btnNapXu.ColorContrastOnHover = 45;
			this.btnNapXu.Cursor = global::System.Windows.Forms.Cursors.Hand;
			borderEdges5.BottomLeft = true;
			borderEdges5.BottomRight = true;
			borderEdges5.TopLeft = true;
			borderEdges5.TopRight = true;
			this.btnNapXu.CustomizableEdges = borderEdges5;
			this.btnNapXu.DialogResult = global::System.Windows.Forms.DialogResult.None;
			this.btnNapXu.DisabledBorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnNapXu.DisabledFillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnNapXu.DisabledForecolor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnNapXu.FocusState = 2;
			this.btnNapXu.Font = new global::System.Drawing.Font("Segoe UI Semibold", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnNapXu.ForeColor = global::System.Drawing.Color.White;
			this.btnNapXu.IconLeftAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnNapXu.IconLeftCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnNapXu.IconLeftPadding = new global::System.Windows.Forms.Padding(11, 3, 3, 3);
			this.btnNapXu.IconMarginLeft = 11;
			this.btnNapXu.IconPadding = 10;
			this.btnNapXu.IconRightAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.btnNapXu.IconRightCursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnNapXu.IconRightPadding = new global::System.Windows.Forms.Padding(3, 3, 7, 3);
			this.btnNapXu.IconSize = 25;
			this.btnNapXu.IdleBorderColor = global::System.Drawing.Color.White;
			this.btnNapXu.IdleBorderRadius = 35;
			this.btnNapXu.IdleBorderThickness = 2;
			this.btnNapXu.IdleFillColor = global::System.Drawing.Color.Transparent;
			this.btnNapXu.IdleIconLeftImage = null;
			this.btnNapXu.IdleIconRightImage = null;
			this.btnNapXu.IndicateFocus = false;
			this.btnNapXu.Location = new global::System.Drawing.Point(86, 505);
			this.btnNapXu.Name = "btnNapXu";
			this.btnNapXu.OnDisabledState.BorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.btnNapXu.OnDisabledState.BorderRadius = 35;
			this.btnNapXu.OnDisabledState.BorderStyle = 0;
			this.btnNapXu.OnDisabledState.BorderThickness = 2;
			this.btnNapXu.OnDisabledState.FillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.btnNapXu.OnDisabledState.ForeColor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.btnNapXu.OnDisabledState.IconLeftImage = null;
			this.btnNapXu.OnDisabledState.IconRightImage = null;
			this.btnNapXu.onHoverState.BorderColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnNapXu.onHoverState.BorderRadius = 35;
			this.btnNapXu.onHoverState.BorderStyle = 0;
			this.btnNapXu.onHoverState.BorderThickness = 2;
			this.btnNapXu.onHoverState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnNapXu.onHoverState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnNapXu.onHoverState.IconLeftImage = null;
			this.btnNapXu.onHoverState.IconRightImage = null;
			this.btnNapXu.OnIdleState.BorderColor = global::System.Drawing.Color.White;
			this.btnNapXu.OnIdleState.BorderRadius = 35;
			this.btnNapXu.OnIdleState.BorderStyle = 0;
			this.btnNapXu.OnIdleState.BorderThickness = 2;
			this.btnNapXu.OnIdleState.FillColor = global::System.Drawing.Color.Transparent;
			this.btnNapXu.OnIdleState.ForeColor = global::System.Drawing.Color.White;
			this.btnNapXu.OnIdleState.IconLeftImage = null;
			this.btnNapXu.OnIdleState.IconRightImage = null;
			this.btnNapXu.OnPressedState.BorderColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnNapXu.OnPressedState.BorderRadius = 35;
			this.btnNapXu.OnPressedState.BorderStyle = 0;
			this.btnNapXu.OnPressedState.BorderThickness = 2;
			this.btnNapXu.OnPressedState.FillColor = global::System.Drawing.Color.WhiteSmoke;
			this.btnNapXu.OnPressedState.ForeColor = global::System.Drawing.Color.FromArgb(46, 51, 73);
			this.btnNapXu.OnPressedState.IconLeftImage = null;
			this.btnNapXu.OnPressedState.IconRightImage = null;
			this.btnNapXu.Size = new global::System.Drawing.Size(131, 49);
			this.btnNapXu.TabIndex = 1;
			this.btnNapXu.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.btnNapXu.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.btnNapXu.TextMarginLeft = 0;
			this.btnNapXu.TextPadding = new global::System.Windows.Forms.Padding(0);
			this.btnNapXu.UseDefaultRadiusAndThickness = true;
			this.btnNapXu.Click += new global::System.EventHandler(this.btnNapXu_Click);
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.WhiteSmoke;
			base.ClientSize = new global::System.Drawing.Size(957, 565);
			base.Controls.Add(this.panel1);
			base.Controls.Add(this.bunifuPages1);
			base.Controls.Add(this.bunifuGradientPanel1);
			this.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "frmLoginUser";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "frmLoginUser";
			base.Load += new global::System.EventHandler(this.frmLoginUser_Load);
			this.bunifuPages1.ResumeLayout(false);
			this.tabPage1.ResumeLayout(false);
			this.tabPage1.PerformLayout();
			this.tabPage2.ResumeLayout(false);
			this.bunifuGradientPanel1.ResumeLayout(false);
			this.bunifuGradientPanel1.PerformLayout();
			this.bunifuPictureBox1.EndInit();
			this.panel1.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04000154 RID: 340
		private global::System.ComponentModel.IContainer components = null;

		// Token: 0x04000155 RID: 341
		private global::Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;

		// Token: 0x04000156 RID: 342
		private global::Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;

		// Token: 0x04000157 RID: 343
		private global::System.Windows.Forms.Label label2;

		// Token: 0x04000158 RID: 344
		private global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSignup1;

		// Token: 0x04000159 RID: 345
		private global::Bunifu.UI.WinForms.BunifuPages bunifuPages1;

		// Token: 0x0400015A RID: 346
		private global::System.Windows.Forms.TabPage tabPage1;

		// Token: 0x0400015B RID: 347
		private global::System.Windows.Forms.TabPage tabPage2;

		// Token: 0x0400015C RID: 348
		private global::System.Windows.Forms.Label label1;

		// Token: 0x0400015D RID: 349
		private global::Bunifu.UI.WinForms.BunifuTextBox txtEmailSigin;

		// Token: 0x0400015E RID: 350
		private global::System.Windows.Forms.Label label3;

		// Token: 0x0400015F RID: 351
		private global::Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;

		// Token: 0x04000160 RID: 352
		private global::Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;

		// Token: 0x04000161 RID: 353
		private global::Bunifu.UI.WinForms.BunifuTextBox txtPassSigin;

		// Token: 0x04000162 RID: 354
		private global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSigin;

		// Token: 0x04000163 RID: 355
		private global::System.Windows.Forms.Button btnClose;

		// Token: 0x04000164 RID: 356
		private global::Bunifu.UI.WinForms.BunifuTextBox txtRePass;

		// Token: 0x04000165 RID: 357
		private global::Bunifu.UI.WinForms.BunifuTextBox txtPassword;

		// Token: 0x04000166 RID: 358
		private global::Bunifu.UI.WinForms.BunifuTextBox txtEmail;

		// Token: 0x04000167 RID: 359
		private global::Bunifu.UI.WinForms.BunifuTextBox txtUserName;

		// Token: 0x04000168 RID: 360
		private global::System.Windows.Forms.Button btnMinimize;

		// Token: 0x04000169 RID: 361
		private global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSigup;

		// Token: 0x0400016A RID: 362
		private global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSigin1;

		// Token: 0x0400016B RID: 363
		private global::Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel1;

		// Token: 0x0400016C RID: 364
		private global::Bunifu.Framework.UI.BunifuCheckbox chkRememe;

		// Token: 0x0400016D RID: 365
		private global::System.Windows.Forms.Panel panel1;

		// Token: 0x0400016E RID: 366
		private global::Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;

		// Token: 0x0400016F RID: 367
		private global::Bunifu.Framework.UI.BunifuDragControl bunifuDragControl2;

		// Token: 0x04000170 RID: 368
		private global::System.Windows.Forms.Label label4;

		// Token: 0x04000171 RID: 369
		private global::System.Windows.Forms.Label lblVersion;

		// Token: 0x04000172 RID: 370
		private global::Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnNapXu;
	}
}
